### ISSUE TITLE
Possible changes prior to enabling automatic scraping of LUP

### ISSUE THREAD

**Issue by noblepayne** [ChanceM/show-scraper-2#1]
I took a quick look at the diff between scraper versions for the most recent episode of LUP. Overall it looks great, but I noticed a couple items we may want to address before switching over.

1.  `Linux Unplugged` -> `LINUX Unplugged`. I don't know why this is the branding for the show, but it is. :shrug:
2. It looks like sponsorship's are added to the links. Since we already have that info displayed elsewhere I don't think this is desired.

I think that's it? The order of the sponsorships is different, but I don't think that matters. `jb_url` and `fireside_url` are also different, but the new versions look better. I do see what looks like maybe an extraneous `value` key in the v2 output? But also shouldn't matter.

Here's the slightly modified diff (additional context: V1's version has extra whitespace before each link, but I removed that for a more meaningful comparison):
```diff
5c5
<   "show_name": "LINUX Unplugged",
---
>   "show_name": "Linux Unplugged",
15c15
<     "LINUX Unplugged"
---
>     "Linux Unplugged"
72d71
<     "memberful.com-lup",
74c73,74
<     "1password.com-lup"
---
>     "1password.com-lup",
>     "memberful.com-lup"
168,169c168,170
<   "jb_url": null,
<   "fireside_url": "/574"
---
>   "jb_url": "https://www.jupiterbroadcasting.com/show/linux-unplugged/574",
>   "fireside_url": "https://linuxunplugged.com/574",
>   "value": null
174a176,178
> * [Core Contributor Membership](https://jupitersignal.memberful.com/checkout?plan=52946&coupon=summer): [Take $1 a month of your membership for a lifetime!](https://jupitersignal.memberful.com/checkout?plan=52946&coupon=summer)
> * [Tailscale](http://tailscale.com/linuxunplugged): [Tailscale is a programmable networking software that is private and secure by default - get it free on up to 100 devices!](http://tailscale.com/linuxunplugged)
> * [1Password Extended Access Management](https://1password.com/unplugged): [1Password Extended Access Management is a device trust solution for companies with Okta, and they ensure that if a device isn't trusted and secure, it can't log into your cloud apps.](https://1password.com/unplugged)
```

With these addressed I think we should go ahead and enable automatic scraping of LUP using V2.

Thanks for all your help!

**Comment by ChanceM** [comment]
Just for visibility, answering here as well.

1. Updated config show name to adhere to branding.
https://github.com/ChanceM/show-scraper-2/blob/ac68d4feef57a614ea3577a196c27c913af8b91a/config.yml#L14

2. Added Loop to filter out sponsor links from the description keying on a[rel='nofollow']
https://github.com/ChanceM/show-scraper-2/blob/60d298b075800be79a4dde1d3cc86ae240034df1/scraper.py#L142-L146

The order of the sponsors is based on the order presented on the fireside page. They do not appear to be sorted the last episodes order is `['m','t','1']` and alpha would go `['1', 'm', 't']` or reversed `['t', 'm', '1']`.

The value entry would be populated form <podcast:value> tag if it occurred in the item.
